Repository comic/grand-challenge.org, pull requests merged in 2020-01, with the labels that each got.

#1096 Exclude unused archives in huge retina archives API endpoint
  app/grandchallenge/retina_api/views.py
Labels: area/ophthalmology-workstation

#1126 Clean up of legacy code
  .github/workflows/ci.yml
  README.rst
  app/config/settings.py
  app/config/urls.py
  app/grandchallenge/challenges/management/commands/copy_challenge.py
  app/grandchallenge/challenges/models.py
  app/grandchallenge/core/management/commands/init_gc_demo.py
  app/grandchallenge/favicons/__init__.py
  app/grandchallenge/favicons/urls.py
  app/grandchallenge/favicons/views.py
  app/grandchallenge/pages/forms.py
  app/grandchallenge/pages/migrations/0003_auto_20200123_1020.py
  app/grandchallenge/pages/models.py
  app/grandchallenge/pages/templates/pages/page_list.html
  app/grandchallenge/pages/urls.py
  app/grandchallenge/pages/views.py
  app/grandchallenge/profiles/templates/userena/profile_detail.html
  app/grandchallenge/statistics/templates/statistics/statistics_detail.html
  app/grandchallenge/statistics/views.py
  app/grandchallenge/subdomains/urls.py
  app/tests/core_tests/integration_tests.py
  app/tests/favicons_tests/__init__.py
  app/tests/favicons_tests/test_views.py
  app/tests/pages_tests/test_pages.py
  app/tests/participants_tests/test_emails.py
  app/tests/statistics_tests/__init__.py
  app/tests/statistics_tests/test_views.py
  cycle_docker_compose.sh
  docker-compose.yml
  docs/getting-started.rst
  docs/requirements.txt
Labels: do-not-merge

#1134 Load archive data as celery task and cache result
  app/config/settings.py
  app/grandchallenge/retina_api/tasks.py
  app/grandchallenge/retina_api/urls.py
  app/grandchallenge/retina_api/views.py
  app/tests/retina_api_tests/test_tasks.py
  app/tests/retina_api_tests/test_views.py
Labels: area/ophthalmology-workstation, priority/p0

#1138 Save archive data to database instead of cache
  app/config/settings.py
  app/grandchallenge/retina_api/admin.py
  app/grandchallenge/retina_api/migrations/0001_initial.py
  app/grandchallenge/retina_api/migrations/__init__.py
  app/grandchallenge/retina_api/models.py
  app/grandchallenge/retina_api/tasks.py
  app/grandchallenge/retina_api/views.py
  app/tests/retina_api_tests/test_tasks.py
  app/tests/retina_api_tests/test_views.py
Labels: area/ophthalmology-workstation
